package com.android.inputmethod.pinyin.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.android.inputmethod.pinyin.greendao.entity.Scan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCAN".
*/
public class ScanDao extends AbstractDao<Scan, Void> {

    public static final String TABLENAME = "SCAN";

    /**
     * Properties of entity Scan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Code = new Property(0, String.class, "code", false, "CODE");
        public final static Property Time = new Property(1, long.class, "time", false, "TIME");
        public final static Property BackOne = new Property(2, String.class, "backOne", false, "BACK_ONE");
        public final static Property BackTwo = new Property(3, String.class, "backTwo", false, "BACK_TWO");
        public final static Property BackThree = new Property(4, String.class, "backThree", false, "BACK_THREE");
    }


    public ScanDao(DaoConfig config) {
        super(config);
    }
    
    public ScanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCAN\" (" + //
                "\"CODE\" TEXT UNIQUE ," + // 0: code
                "\"TIME\" INTEGER NOT NULL ," + // 1: time
                "\"BACK_ONE\" TEXT," + // 2: backOne
                "\"BACK_TWO\" TEXT," + // 3: backTwo
                "\"BACK_THREE\" TEXT);"); // 4: backThree
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Scan entity) {
        stmt.clearBindings();
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(1, code);
        }
        stmt.bindLong(2, entity.getTime());
 
        String backOne = entity.getBackOne();
        if (backOne != null) {
            stmt.bindString(3, backOne);
        }
 
        String backTwo = entity.getBackTwo();
        if (backTwo != null) {
            stmt.bindString(4, backTwo);
        }
 
        String backThree = entity.getBackThree();
        if (backThree != null) {
            stmt.bindString(5, backThree);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Scan entity) {
        stmt.clearBindings();
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(1, code);
        }
        stmt.bindLong(2, entity.getTime());
 
        String backOne = entity.getBackOne();
        if (backOne != null) {
            stmt.bindString(3, backOne);
        }
 
        String backTwo = entity.getBackTwo();
        if (backTwo != null) {
            stmt.bindString(4, backTwo);
        }
 
        String backThree = entity.getBackThree();
        if (backThree != null) {
            stmt.bindString(5, backThree);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Scan readEntity(Cursor cursor, int offset) {
        Scan entity = new Scan( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // code
            cursor.getLong(offset + 1), // time
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // backOne
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // backTwo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // backThree
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Scan entity, int offset) {
        entity.setCode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTime(cursor.getLong(offset + 1));
        entity.setBackOne(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBackTwo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBackThree(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Scan entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Scan entity) {
        return null;
    }

    @Override
    public boolean hasKey(Scan entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
